"""Game module for brain-gcd game."""
from random import randint

GAME_RULES = 'Find the greatest common divisor of given numbers.'

START_RANGE = 1
END_RANGE = 100


def start_round():
    """
    Generate a random expression and answer for game.

    Returns:
        exrpession to solve and answer on game.
    """
    number1 = randint(START_RANGE, END_RANGE)
    number2 = randint(START_RANGE, END_RANGE)
    question = '{0} {1}'.format(number1, number2)
    answer = get_gcd(number1, number2)
    return question, answer


def get_gcd(num1, num2):
    """
    Find greatest common divisor for brain-gcd game.

    Args:
        num1 : random number generated by brain_gcd.
        num2 : random number generated by brain_gcd.

    Returns:
        GCD for numbers.
    """
    while num1 != 0 and num2 != 0:
        if num1 > num2:
            num1 %= num2
        else:
            num2 %= num1
    return '{0}'.format(num1 + num2)
