"""Game module for brain-gcd game."""
from random import randint

GAME_RULES = 'Find the greatest common divisor of given numbers.'


def main():
    """
    Generate a random expression and answer for game.

    Returns:
        exrpession to solve and answer on it.
    """
    num1 = randint(1, 50)
    num2 = randint(1, 50)
    question = '{0} {1}'.format(num1, num2)
    answer = get_gcd(num1, num2)
    return question, answer


def get_gcd(num1, num2):
    """
    Find greatest common divisor for brain-gcd game.

    Args:
        num1 : random number generated by brain_gcd.
        num2 : random number generated by brain_gcd.

    Returns:
        GCD for numbers.
    """
    while num1 != 0 and num2 != 0:
        if num1 > num2:
            num1 %= num2
        else:
            num2 %= num1
    return '{0}'.format(num1 + num2)
